package charger

// Code generated by github.com/evcc-io/evcc/cmd/tools/decorate.go. DO NOT EDIT.

import (
	"github.com/evcc-io/evcc/api"
)

func decorateWarp(base *Warp, meter func() (float64, error), meterEnergy func() (float64, error), meterCurrent func() (float64, float64, float64, error), identifier func() (string, error)) api.Charger {
	switch {
	case identifier == nil && meter == nil && meterCurrent == nil && meterEnergy == nil:
		return base

	case identifier == nil && meter != nil && meterCurrent == nil && meterEnergy == nil:
		return &struct {
			*Warp
			api.Meter
		}{
			Warp: base,
			Meter: &decorateWarpMeterImpl{
				meter: meter,
			},
		}

	case identifier == nil && meter == nil && meterCurrent == nil && meterEnergy != nil:
		return &struct {
			*Warp
			api.MeterEnergy
		}{
			Warp: base,
			MeterEnergy: &decorateWarpMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
		}

	case identifier == nil && meter != nil && meterCurrent == nil && meterEnergy != nil:
		return &struct {
			*Warp
			api.Meter
			api.MeterEnergy
		}{
			Warp: base,
			Meter: &decorateWarpMeterImpl{
				meter: meter,
			},
			MeterEnergy: &decorateWarpMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
		}

	case identifier == nil && meter == nil && meterCurrent != nil && meterEnergy == nil:
		return &struct {
			*Warp
			api.MeterCurrent
		}{
			Warp: base,
			MeterCurrent: &decorateWarpMeterCurrentImpl{
				meterCurrent: meterCurrent,
			},
		}

	case identifier == nil && meter != nil && meterCurrent != nil && meterEnergy == nil:
		return &struct {
			*Warp
			api.Meter
			api.MeterCurrent
		}{
			Warp: base,
			Meter: &decorateWarpMeterImpl{
				meter: meter,
			},
			MeterCurrent: &decorateWarpMeterCurrentImpl{
				meterCurrent: meterCurrent,
			},
		}

	case identifier == nil && meter == nil && meterCurrent != nil && meterEnergy != nil:
		return &struct {
			*Warp
			api.MeterCurrent
			api.MeterEnergy
		}{
			Warp: base,
			MeterCurrent: &decorateWarpMeterCurrentImpl{
				meterCurrent: meterCurrent,
			},
			MeterEnergy: &decorateWarpMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
		}

	case identifier == nil && meter != nil && meterCurrent != nil && meterEnergy != nil:
		return &struct {
			*Warp
			api.Meter
			api.MeterCurrent
			api.MeterEnergy
		}{
			Warp: base,
			Meter: &decorateWarpMeterImpl{
				meter: meter,
			},
			MeterCurrent: &decorateWarpMeterCurrentImpl{
				meterCurrent: meterCurrent,
			},
			MeterEnergy: &decorateWarpMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
		}

	case identifier != nil && meter == nil && meterCurrent == nil && meterEnergy == nil:
		return &struct {
			*Warp
			api.Identifier
		}{
			Warp: base,
			Identifier: &decorateWarpIdentifierImpl{
				identifier: identifier,
			},
		}

	case identifier != nil && meter != nil && meterCurrent == nil && meterEnergy == nil:
		return &struct {
			*Warp
			api.Identifier
			api.Meter
		}{
			Warp: base,
			Identifier: &decorateWarpIdentifierImpl{
				identifier: identifier,
			},
			Meter: &decorateWarpMeterImpl{
				meter: meter,
			},
		}

	case identifier != nil && meter == nil && meterCurrent == nil && meterEnergy != nil:
		return &struct {
			*Warp
			api.Identifier
			api.MeterEnergy
		}{
			Warp: base,
			Identifier: &decorateWarpIdentifierImpl{
				identifier: identifier,
			},
			MeterEnergy: &decorateWarpMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
		}

	case identifier != nil && meter != nil && meterCurrent == nil && meterEnergy != nil:
		return &struct {
			*Warp
			api.Identifier
			api.Meter
			api.MeterEnergy
		}{
			Warp: base,
			Identifier: &decorateWarpIdentifierImpl{
				identifier: identifier,
			},
			Meter: &decorateWarpMeterImpl{
				meter: meter,
			},
			MeterEnergy: &decorateWarpMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
		}

	case identifier != nil && meter == nil && meterCurrent != nil && meterEnergy == nil:
		return &struct {
			*Warp
			api.Identifier
			api.MeterCurrent
		}{
			Warp: base,
			Identifier: &decorateWarpIdentifierImpl{
				identifier: identifier,
			},
			MeterCurrent: &decorateWarpMeterCurrentImpl{
				meterCurrent: meterCurrent,
			},
		}

	case identifier != nil && meter != nil && meterCurrent != nil && meterEnergy == nil:
		return &struct {
			*Warp
			api.Identifier
			api.Meter
			api.MeterCurrent
		}{
			Warp: base,
			Identifier: &decorateWarpIdentifierImpl{
				identifier: identifier,
			},
			Meter: &decorateWarpMeterImpl{
				meter: meter,
			},
			MeterCurrent: &decorateWarpMeterCurrentImpl{
				meterCurrent: meterCurrent,
			},
		}

	case identifier != nil && meter == nil && meterCurrent != nil && meterEnergy != nil:
		return &struct {
			*Warp
			api.Identifier
			api.MeterCurrent
			api.MeterEnergy
		}{
			Warp: base,
			Identifier: &decorateWarpIdentifierImpl{
				identifier: identifier,
			},
			MeterCurrent: &decorateWarpMeterCurrentImpl{
				meterCurrent: meterCurrent,
			},
			MeterEnergy: &decorateWarpMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
		}

	case identifier != nil && meter != nil && meterCurrent != nil && meterEnergy != nil:
		return &struct {
			*Warp
			api.Identifier
			api.Meter
			api.MeterCurrent
			api.MeterEnergy
		}{
			Warp: base,
			Identifier: &decorateWarpIdentifierImpl{
				identifier: identifier,
			},
			Meter: &decorateWarpMeterImpl{
				meter: meter,
			},
			MeterCurrent: &decorateWarpMeterCurrentImpl{
				meterCurrent: meterCurrent,
			},
			MeterEnergy: &decorateWarpMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
		}
	}

	return nil
}

type decorateWarpIdentifierImpl struct {
	identifier func() (string, error)
}

func (impl *decorateWarpIdentifierImpl) Identify() (string, error) {
	return impl.identifier()
}

type decorateWarpMeterImpl struct {
	meter func() (float64, error)
}

func (impl *decorateWarpMeterImpl) CurrentPower() (float64, error) {
	return impl.meter()
}

type decorateWarpMeterCurrentImpl struct {
	meterCurrent func() (float64, float64, float64, error)
}

func (impl *decorateWarpMeterCurrentImpl) Currents() (float64, float64, float64, error) {
	return impl.meterCurrent()
}

type decorateWarpMeterEnergyImpl struct {
	meterEnergy func() (float64, error)
}

func (impl *decorateWarpMeterEnergyImpl) TotalEnergy() (float64, error) {
	return impl.meterEnergy()
}
